create table if not exists public.telegram_error_events (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    userbot_id uuid null,
    account_id uuid null,
    channel_id uuid null,
    subscription_id uuid null,
    campaign_id bigint null,
    tg_user_id text null,
    event_source text not null default 'telegram',
    event_type text not null default 'unknown',
    severity text not null default 'warning',
    restriction_kind text not null default 'unknown',
    is_restriction boolean not null default false,
    error_code text null,
    error_message text null,
    happened_at timestamptz not null default now(),
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists telegram_error_events_owner_happened_idx
    on public.telegram_error_events (owner_id, happened_at desc);

create index if not exists telegram_error_events_userbot_happened_idx
    on public.telegram_error_events (userbot_id, happened_at desc);

create index if not exists telegram_error_events_restriction_idx
    on public.telegram_error_events (owner_id, is_restriction, happened_at desc);
